__version__ = "0.0.2"
import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'adaboost',
        'big_data_analytics',
        'core',
        'digital_processing_of_speech_signals',
        'help',
        'svm',
        'tree',
    },
    submod_attrs={
        'adaboost': [
            'calculate_gini_index',
            'calculate_gini_index_for_subset',
            'plot_binary_classification_3d',
            'vis',
        ],
        'big_data_analytics': [
            'MatrixFactorization',
            'MatrixFactorizationSetting',
            'anova',
            'anova_oneway',
            'auto_anova_for_df',
            'auto_friedman_for_df',
            'auto_kruskal_for_df',
            'compute_weighted_sum_on_matrix',
            'draw_box',
            'draw_hist',
            'draw_metrics_df',
            'ensure_tensor',
            'fixed_meta_params',
            'frozen_rvs',
            'get_X_train_weighted',
            'get_rating_matrix',
            'get_similarities',
            'homogeneity_of_variance',
            'jax_masked_mse_loss',
            'masked_mse_loss',
            'masked_rmse_loss',
            'matrix_decomposition',
            'objective',
            'sqlite_url',
            'study',
            'study_path',
            'test_normality_group',
            'test_normality_small_sample',
            'train_matrix_factorization',
        ],
        'core': [
            'foo',
        ],
        'digital_processing_of_speech_signals': [
            'HiddenMarkovModel',
            'hidden_markov_model',
        ],
        'help': [
            'data_path',
            'font',
            'joblib_memory',
            'lib_directory_path',
            'lib_init_path',
            'lib_repo_path',
            'original_show_doc',
            'runs_figs_path',
            'runs_path',
            'show_doc',
        ],
        'svm': [
            'BinaryHingeLoss',
            'HingeSupportVectorClassifier',
            'KernelSupportVectorClassifier',
            'MultiClassHingeLoss',
            'ReturnType',
            'Strategy',
            'SupportVectorClassifierConfig',
            'dict_to_dataclass',
            'draw_probs',
            'evaluate_svm',
            'fixed_meta_params',
            'frozen_rvs',
            'get_max_values_without_true',
            'get_torch_dataset',
            'handy_crafted',
            'infra',
            'kernel',
            'kernel_hpo',
            'linear',
            'make_meshgrid',
            'make_train_val_test',
            'objective_svm',
            'plot_binary_classification_2d',
            'plot_contours',
            'process_sklearn_dataset_dict',
            'scheduler_lmd_leon_bottou_asgd',
            'scheduler_lmd_leon_bottou_sgd',
            'separate_weight_decay',
            'sklearn_to_X_y_categories',
            'sqlite_url',
            'study',
            'study_path',
            'try_svm_and_plot_for_binary_2d',
            'use_lib',
            'vis',
        ],
        'tree': [
            'FastKDTree',
            'Node',
            'build_kd_tree',
            'euclidean_distance',
            'evaluate_knn',
            'fast_build_kd_tree',
            'fast_search_kd_tree',
            'knn_classifier',
            'objective',
            'regplot',
            'search_kd_tree',
            'search_space',
            'verbose',
        ],
    },
)

__all__ = ['BinaryHingeLoss', 'FastKDTree', 'HiddenMarkovModel',
           'HingeSupportVectorClassifier', 'KernelSupportVectorClassifier',
           'MatrixFactorization', 'MatrixFactorizationSetting',
           'MultiClassHingeLoss', 'Node', 'ReturnType', 'Strategy',
           'SupportVectorClassifierConfig', 'adaboost', 'anova',
           'anova_oneway', 'auto_anova_for_df', 'auto_friedman_for_df',
           'auto_kruskal_for_df', 'big_data_analytics', 'build_kd_tree',
           'calculate_gini_index', 'calculate_gini_index_for_subset',
           'compute_weighted_sum_on_matrix', 'core', 'data_path',
           'dict_to_dataclass', 'digital_processing_of_speech_signals',
           'draw_box', 'draw_hist', 'draw_metrics_df', 'draw_probs',
           'ensure_tensor', 'euclidean_distance', 'evaluate_knn',
           'evaluate_svm', 'fast_build_kd_tree', 'fast_search_kd_tree',
           'fixed_meta_params', 'font', 'foo', 'frozen_rvs',
           'get_X_train_weighted', 'get_max_values_without_true',
           'get_rating_matrix', 'get_similarities', 'get_torch_dataset',
           'handy_crafted', 'help', 'hidden_markov_model',
           'homogeneity_of_variance', 'infra', 'jax_masked_mse_loss',
           'joblib_memory', 'kernel', 'kernel_hpo', 'knn_classifier',
           'lib_directory_path', 'lib_init_path', 'lib_repo_path', 'linear',
           'make_meshgrid', 'make_train_val_test', 'masked_mse_loss',
           'masked_rmse_loss', 'matrix_decomposition', 'objective',
           'objective_svm', 'original_show_doc',
           'plot_binary_classification_2d', 'plot_binary_classification_3d',
           'plot_contours', 'process_sklearn_dataset_dict', 'regplot',
           'runs_figs_path', 'runs_path', 'scheduler_lmd_leon_bottou_asgd',
           'scheduler_lmd_leon_bottou_sgd', 'search_kd_tree', 'search_space',
           'separate_weight_decay', 'show_doc', 'sklearn_to_X_y_categories',
           'sqlite_url', 'study', 'study_path', 'svm', 'test_normality_group',
           'test_normality_small_sample', 'train_matrix_factorization', 'tree',
           'try_svm_and_plot_for_binary_2d', 'use_lib', 'verbose', 'vis']
