# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/THU-Coursework-Machine-Learning-for-Big-Data',
                'doc_host': 'https://Open-Book-Studio.github.io',
                'git_url': 'https://github.com/Open-Book-Studio/THU-Coursework-Machine-Learning-for-Big-Data',
                'lib_path': 'thu_big_data_ml'},
  'syms': {'thu_big_data_ml.core': {'thu_big_data_ml.core.foo': ('core.html#foo', 'thu_big_data_ml/core.py')}}}
