"""本库的一些信息"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_help (library information).ipynb.

# %% auto 0
__all__ = ['lib_init_path', 'lib_directory_path', 'lib_repo_path', 'runs_path', 'runs_figs_path', 'data_path']

# %% ../notebooks/00_help (library information).ipynb 4
from pathlib import Path
import inspect
import thu_big_data_ml as this_library
lib_init_path = Path(inspect.getfile(this_library))
lib_directory_path = lib_init_path.parent
lib_repo_path = lib_directory_path.parent
runs_path = lib_repo_path/'runs'
runs_path.mkdir(exist_ok=True, parents=True)
runs_figs_path = runs_path/'figs'
runs_figs_path.mkdir(exist_ok=True, parents=True)
data_path = lib_repo_path/'data'
data_path.mkdir(exist_ok=True, parents=True)
