# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/coding_projects/P2_SVM/04svm_handy_crafted_kernel.ipynb.

# %% auto 0
__all__ = ['SupportVectorClassifier']

# %% ../../../notebooks/coding_projects/P2_SVM/04svm_handy_crafted_kernel.ipynb 4
from fastcore.all import patch, store_attr
class SupportVectorClassifier:
    """自己实现的支持向量机分类器。需要支持多分类。
    """
    def __init__(self, config:SupportVectorClassifierConfig):
        store_attr()
        
